# Generated by Django 4.2.5 on 2023-09-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmeseciton',
            old_name='desctiprion',
            new_name='descriprion',
        ),
        migrations.AddField(
            model_name='aboutmeseciton',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Drive Image Id'),
        ),
        migrations.AddField(
            model_name='aboutmeseciton',
            name='linkToCV',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='URL link for CV'),
        ),
        migrations.AlterField(
            model_name='smlinks',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon eg: bx-linkedin'),
        ),
    ]
