# Generated by Django 4.2.5 on 2023-09-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroAnother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='just to fill space')),
            ],
        ),
    ]
