# Generated by Django 4.2.5 on 2023-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForPortfolio', '0002_introanother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introbannerhero',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='check'),
        ),
        migrations.AlterField(
            model_name='introbannerhero',
            name='welcomeText',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
