# Generated by Django 4.2.5 on 2023-09-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForPortfolio', '0003_alter_introbannerhero_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introbannerhero',
            options={'verbose_name': 'Intro Banner Text'},
        ),
        migrations.AddField(
            model_name='introbannerhero',
            name='emailAddress',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Your personal email to recieve emails on'),
        ),
        migrations.AddField(
            model_name='introbannerhero',
            name='image',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Google Drive id only for image'),
        ),
        migrations.AddField(
            model_name='introbannerhero',
            name='introPara',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Introduction Paragraph'),
        ),
        migrations.AddField(
            model_name='introbannerhero',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='introbannerhero',
            name='linkToCV',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='URL link for CV'),
        ),
        migrations.AlterField(
            model_name='introbannerhero',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Your Full Name'),
        ),
        migrations.AlterField(
            model_name='introbannerhero',
            name='welcomeText',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Text to welcome users'),
        ),
    ]
