# Generated by Django 4.2.5 on 2023-09-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appForPortfolio', '0004_alter_introbannerhero_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeSeciton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Title for About me Section')),
                ('subTitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle')),
                ('desctiprion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrition')),
            ],
            options={
                'verbose_name': 'About me Section Text',
            },
        ),
        migrations.DeleteModel(
            name='IntroAnother',
        ),
    ]
